language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -q -r requirements.txt
  - pip install -q tensorflow
  - pip install -q pytest-xdist
# command to run tests
script: PYTHONPATH=src python3 -m pytest --cache-clear --ignore=src/spn/tests/test_tree_viz.py --ignore=src/spn/tests/test_cpp.py src/spn/tests/
#python3 -m unittest discover src/spn