language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install tensorflow
  - pip install cppyy
  - pip install pytest-xdist
# command to run tests
script: PYTHONPATH=src python3 -m pytest --cache-clear --ignore=src/spn/tests/test_tree_viz.py src/spn/tests/
#python3 -m unittest discover src/spn