language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install tensorflow
  - pip install pytest-xdist
# command to run tests
script: PYTHONPATH=src python3 -m pytest --boxed --cache-clear  src/spn/tests/
#python3 -m unittest discover src/spn